"""Added users table

Revision ID: 8167dfa51bce
Revises:
Create Date: 2024-10-06 12:48:55.449041

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8167dfa51bce"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("user",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("age", sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
