"""Added account holder table

Revision ID: 99669abce3e8
Revises: 1852e4859683
Create Date: 2024-10-07 21:28:03.803524

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "99669abce3e8"
down_revision: str | None = "1852e4859683"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("accountholder",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("user_id", sa.Integer(), nullable=False),
    sa.Column("account_id", sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(["account_id"], ["account.id"] ),
    sa.ForeignKeyConstraint(["user_id"], ["user.id"] ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("account_id"),
    sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("accountholder")
    # ### end Alembic commands ###
